In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sravai\anaconda3\lib\site-packages (1.0.5)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\sravai\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\sravai\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\sravai\anaconda3\lib\site-packages (from pandas) (1.18.5)
Requirement already satisfied: six>=1.5 in c:\users\sravai\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel(r'C:\Users\sravai\downloads\data.xlsx')
df.head()

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000,2012-06-01,present,senior quality engineer,Bangalore,f,1990-02-19,84.3,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.35490,-0.4455
1,train,579905,500000,2013-09-01,present,assistant manager,Indore,m,1989-10-04,85.4,...,-1,-1,-1,-1,-1,-0.7335,0.3789,1.2396,-0.10760,0.8637
2,train,810601,325000,2014-06-01,present,systems engineer,Chennai,f,1992-08-03,85.0,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.86820,0.6721
3,train,267447,1100000,2011-07-01,present,senior software engineer,Gurgaon,m,1989-12-05,85.6,...,-1,-1,-1,-1,-1,0.0464,0.3448,-0.3440,-0.40780,-0.9194
4,train,343523,200000,2014-03-01,2015-03-01 00:00:00,get,Manesar,m,1991-02-27,78.0,...,-1,-1,-1,-1,-1,-0.8810,-0.2793,-1.0697,0.09163,-0.1295

# To retrive only specialization

In [23]:
df=pd.read_excel(r'C:\Users\sravai\downloads\data.xlsx')
new_df = df.groupby('Specialization')
new_df.first()

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
Specialization,,,,,,,,,,,,,,,,,,,,,
aeronautical engineering,train,593198,120000,2013-06-01,2014-04-01 00:00:00,cad designer,Hyderabad,m,1991-11-10,74.00,...,-1,-1,-1,-1,-1,0.2718,0.2124,0.0100,0.27270,-0.0943
applied electronics and instrumentation,train,1044453,310000,2014-02-01,2014-05-01 00:00:00,system engineer,Mysore,m,1990-12-02,89.37,...,-1,-1,-1,-1,-1,0.9900,1.2114,-0.2974,-1.12180,1.2470
automobile/automotive engineering,train,676834,380000,2014-01-01,present,assistant system engineer,Hyderabad,m,1992-01-18,82.00,...,-1,366,-1,-1,-1,0.7027,0.8784,0.4711,-1.50210,0.0973
biomedical engineering,train,280764,145000,2011-06-01,2013-08-01 00:00:00,sales executive,Gurgaon,f,1990-03-26,82.20,...,-1,-1,-1,-1,-1,-1.0355,-0.1232,-1.2148,0.06230,0.3444
biotechnology,train,318523,400000,2012-06-01,present,systems engineer,Hyderabad,m,1991-06-20,87.00,...,-1,-1,-1,-1,-1,1.3215,1.4368,2.1234,-1.05407,0.0284
ceramic engineering,train,945679,335000,2014-06-01,2015-01-01 00:00:00,quality assurance engineer,Mumbai,m,1991-09-27,93.33,...,-1,-1,-1,-1,-1,0.5591,0.3789,-0.1437,-0.23440,0.6721
chemical engineering,train,914981,200000,2014-01-01,2014-02-01 00:00:00,marketing executive,-1,m,1988-04-18,88.00,...,-1,-1,-1,-1,-1,0.4155,0.5454,1.3933,-0.99500,0.6721
civil engineering,train,1089283,110000,2014-06-01,2015-02-01 00:00:00,assistant professor,Una,f,1993-04-15,70.00,...,-1,-1,-1,-1,388,-0.0154,1.2114,1.3933,-0.86820,1.6302
computer and communication engineering,train,1111630,120000,2014-08-01,present,software engineer,New Delhi,m,1993-04-27,82.28,...,500,-1,-1,-1,-1,0.2718,0.7119,1.3933,-2.26270,0.2889
computer application,train,874596,250000,2013-08-01,2014-09-01 00:00:00,associate software developer,Gurgaon,m,1987-09-28,60.80,...,500,-1,-1,-1,-1,0.8463,1.0449,-1.0659,-1.62890,0.6721
computer engineering,train,203097,420000,2012-06-01,present,senior quality engineer,Bangalore,f,1990-02-19,84.30,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.35490,-0.4455
computer networking,train,353442,565000,2014-07-01,present,r&d engineer,-1,m,1990-09-14,91.00,...,-1,-1,-1,-1,-1,-0.6491,0.3448,0.0914,-0.34900,-1.5513
computer science,train,1250504,400000,2014-09-01,2015-02-01 00:00:00,associate software engg,Hyderabad,m,1990-02-25,69.50,...,500,-1,-1,-1,-1,0.9900,-0.2871,0.7785,-1.62890,-0.8608
computer science & engineering,train,947847,300000,2014-08-01,2015-05-01 00:00:00,java software engineer,Banglore,m,1993-02-01,86.08,...,346,-1,-1,-1,-1,1.7081,-0.1054,-1.0379,-2.00920,-1.0872
computer science and technology,train,983664,300000,2015-06-01,2015-06-01 00:00:00,software engineer,Noida,m,1993-04-09,88.00,...,407,-1,-1,-1,-1,-0.1590,-0.4536,-0.2974,0.52620,-1.0524
control and instrumentation engineering,train,1081403,305000,2014-12-01,present,software engineer,pune,m,1992-01-01,88.20,...,-1,-1,-1,-1,-1,0.9900,1.5444,-0.4511,-1.37530,-0.8608
electrical and power engineering,train,978959,240000,2014-06-01,2015-03-01 00:00:00,maintenance engineer,-1,m,1992-07-14,88.17,...,-1,-1,-1,-1,-1,1.9953,1.3779,1.0859,-1.37530,1.0554
electrical engineering,train,1082717,350000,2014-09-01,present,assistant system engineer,Mumbai,m,1991-08-06,89.25,...,-1,-1,484,-1,-1,-0.1590,-0.1206,-0.6048,-1.62890,-1.4356
electronics,train,578157,40000,2013-10-01,2014-07-01 00:00:00,application developer,Bangalore,m,1991-04-01,64.00,...,-1,-1,-1,-1,-1,1.8517,0.2124,2.1617,-2.00920,-0.2859
electronics & instrumentation eng,train,1059903,300000,2012-07-01,present,production engineer,Indore,m,1989-12-08,63.40,...,-1,-1,-1,-1,-1,-0.4463,-1.1196,-1.6807,-0.48790,-1.2440
electronics & telecommunications,train,606655,270000,2013-12-01,present,quality assurance engineer,Pune,m,1990-11-21,83.60,...,-1,-1,-1,206,-1,0.1282,0.5454,-0.7585,-0.99500,0.8637
electronics and communication engineering,train,579905,500000,2013-09-01,present,assistant manager,Indore,m,1989-10-04,85.40,...,-1,-1,-1,-1,-1,-0.7335,0.3789,1.2396,-0.10760,0.8637
electronics and computer engineering,train,852310,120000,2015-02-01,present,ui developer,Hyderabad,m,1991-11-03,80.00,...,-1,-1,-1,-1,-1,-0.4463,-0.1206,-1.0659,-0.10760,-1.2440
electronics and electrical engineering,train,552574,600000,2013-07-01,present,electrical engineer,Noida,m,1991-09-17,90.00,...,-1,-1,-1,-1,-1,-0.1590,0.5454,-0.6048,-0.74150,-0.2859
electronics and instrumentation engineering,train,543139,110000,2014-04-01,2014-06-01 00:00:00,engineer,new delhi - jaisalmer,m,1990-11-06,66.80,...,-1,-1,-1,-1,-1,-1.4606,-0.2793,-0.9245,1.06110,-0.7615
electronics engineering,train,431838,330000,2013-01-01,present,operation engineer,-1,m,1990-02-10,86.80,...,-1,-1,-1,-1,-1,-0.9969,-0.7473,-0.3440,-0.26090,-2.1833
embedded systems technology,train,918414,200000,2008-11-01,2012-11-01 00:00:00,project engineer,Thiruvananthapuram,m,1986-05-27,49.00,...,-1,-1,-1,-1,-1,-1.1644,-1.9521,-1.0659,0.52620,-1.4356
industrial & management engineering,train,1229820,320000,2014-12-01,present,systems engineer,Bangalore,m,1992-08-15,80.33,...,-1,-1,-1,-1,-1,0.9900,0.5454,0.4711,-1.62890,-2.2021
industrial & production engineering,train,134828,180000,2010-09-01,2011-11-01 00:00:00,junior engineer,vsakhapttnam,m,1989-05-10,76.70,...,-1,286,-1,-1,-1,-0.2628,-0.2793,-1.2148,0.88480,-0.2875
industrial engineering,train,711754,390000,2013-12-01,present,business analyst,Noida,m,1989-10-28,82.00,...,-1,-1,-1,-1,-1,0.9900,1.3779,1.2396,-0.23440,-0.2859
information & communication technology,train,896880,450000,2014-08-01,2015-04-01 00:00:00,programmer analyst,Bangalore,f,1992-10-08,89.00,...,469,-1,-1,-1,-1,0.7027,1.2114,0.3174,-1.50210,-0.0943
information science,train,552431,460000,2013-05-01,present,software engineer,Gandhinagar,m,1991-02-12,73.00,...,-1,-1,-1,-1,-1,-0.3027,-2.6181,-1.9881,-1.12180,-1.4356
information science engineering,train,991197,100000,2014-10-01,2015-01-01 00:00:00,web developer,Mysore,m,1993-01-16,78.00,...,438,-1,-1,-1,-1,-2.3134,-0.1206,-0.2974,0.14590,-1.6273
information technology,train,810601,325000,2014-06-01,present,systems engineer,Chennai,f,1992-08-03,85.00,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.86820,0.6721
instrumentation and control engineering,train,1279958,300000,2013-07-01,present,java software engineer,Bangalore,m,1992-07-02,81.20,...,376,-1,-1,-1,-1,0.7027,0.7119,0.0100,-0.99500,0.6721
instrumentation engineering,train,708034,260000,2013-09-01,present,quality associate,Bangalore,m,1990-12-20,65.00,...,-1,-1,-1,-1,-1,-0.8772,-0.1206,0.1637,1.28690,1.2470
internal combustion engine,train,1067508,360000,2015-02-01,2015-04-01 00:00:00,test engineer,Chennai,m,1990-09-04,76.00,...,-1,438,-1,-1,-1,0.4155,0.0459,-0.4511,-0.36120,-0.8608
mechanical & production engineering,train,242799,100000,2011-10-01,2012-04-01 00:00:00,service coordinator,Bangalore,m,1989-10-03,65.00,...,-1,313,-1,-1,-1,-0.5719,-1.2153,-1.5051,0.76730,-1.7093
mechanical and automation,train,320969,500000,2012-08-01,present,senior engineer,Mysore,m,1989-07-06,84.00,...,-1,383,-1,-1,-1,-0.4173,1.1248,-0.1988,0.88483,0.1864
mechanical engineering,train,912934,400000,2014-07-01,2015-07-01 00:00:00,mechanical engineer,Bangalore,m,1992-05-27,92.00,...,-1,469,-1,-1,-1,-0.0154,1.2114,0.0100,0.14590,1.2470
mechatronics,train,879126,350000,2014-09-01,present,software engineer,Pune,f,1989-08-22,85.06,...,-1,-1,-1,-1,-1,-1.5953,-1.1196,-1.0659,-1.24860,-0.2859
metallurgical engineering,train,1045625,300000,2015-02-01,present,software engineer,Bangalore,m,1992-09-11,89.50,...,-1,-1,-1,-1,-1,-2.7443,0.2124,-1.5270,1.16010,-0.2859
other,train,611740,300000,2013-11-01,2015-05-01 00:00:00,project engineer,Hyderabad,m,1992-06-03,78.20,...,-1,-1,-1,-1,-1,-0.1590,0.3789,-1.0659,-0.86820,-0.0943
polymer technology,train,962376,700000,2014-07-01,present,product manager,Jaipur,m,1992-01-03,87.40,...,-1,-1,-1,-1,-1,-0.3027,-0.4536,-0.6048,-0.86820,0.0973
power systems and automation,train,652877,100000,2013-06-01,2014-07-01 00:00:00,maintenance engineer,Miryalaguda,m,1992-04-03,82.50,...,-1,-1,452,-1,-1,-0.1590,-0.4536,-1.3733,-0.99500,1.0554
telecommunication engineering,train,897769,400000,2014-07-01,present,software engineer,Bangalore,m,1992-10-27,82.56,...,-1,-1,-1,366,-1,-0.4463,-0.6201,0.1637,1.03330,1.0554

# To know the maximum salary from the given data set

In [20]:

df[df.Salary==df.Salary.max()]

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
1237,train,48107,4000000,2010-07-01,2015-03-01 00:00:00,senior software engineer,New Delhi,m,1987-09-09,90.83,...,-1,-1,-1,-1,-1,-0.7264,0.0328,-1.6502,-0.8778,-0.1295
2182,train,41147,4000000,2010-01-01,2011-12-01 00:00:00,automation engineer,gurgaon,m,1987-09-13,53.00,...,-1,-1,-1,-1,-1,-3.3539,-0.4353,-1.0697,-0.0552,-2.6572

# To retrive only female in the given data set

In [8]:
df.loc[df.Gender=='f',:]

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000,2012-06-01,present,senior quality engineer,Bangalore,f,1990-02-19,84.30,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.35490,-0.4455
2,train,810601,325000,2014-06-01,present,systems engineer,Chennai,f,1992-08-03,85.00,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.86820,0.6721
15,train,536517,350000,2013-08-01,present,network engineer,-1,f,1990-01-17,69.54,...,-1,-1,-1,-1,-1,1.7465,1.9048,0.6720,-0.29020,1.2528
19,train,466888,325000,2014-09-01,present,software engineer,Pune,f,1990-11-30,79.00,...,-1,-1,-1,-1,-1,0.8192,0.2668,-0.2714,-0.40780,-0.1295
20,train,140069,320000,2010-11-01,2012-09-01 00:00:00,software engineer,Bangalore,f,1988-07-25,91.20,...,-1,-1,-1,-1,-1,-0.1082,0.9688,0.5269,-0.29020,0.3444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3988,train,466661,200000,2013-02-01,2013-07-01 00:00:00,data analyst,Bangalore,f,1991-05-15,74.40,...,-1,-1,-1,-1,-1,-0.5332,-0.1232,-0.0537,1.32550,0.5024
3990,train,204287,480000,2012-02-01,present,senior systems engineer,Hyderabad,f,1989-09-04,88.00,...,-1,-1,-1,233,-1,0.6646,0.3448,0.3817,-1.34780,0.8183
3994,train,752781,100000,2013-07-01,2013-07-01 00:00:00,technical writer,Hyderabad,f,1992-08-27,90.00,...,-1,-1,-1,-1,-1,-0.3027,0.8784,0.9322,0.77980,-0.0943
3996,train,947111,200000,2014-07-01,2015-01-01 00:00:00,software developer,Asifabadbanglore,f,1992-03-20,78.72,...,438,-1,-1,-1,-1,-0.1590,0.0459,-0.4511,-0.36120,-0.0943
3997,train,324966,400000,2013-02-01,present,senior systems engineer,Chennai,f,1991-02-26,70.60,...,-1,-1,-1,-1,-1,-1.1128,-0.2793,-0.6343,1.32553,-0.6035

# To retrive details of system engineers from Hyderabad

In [4]:
df.loc[(df.JobCity=='Hyderabad')&(df.Designation=='system engineer')]

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
5,train,1027655,300000,2014-06-01,present,system engineer,Hyderabad,m,1992-07-02,89.92,...,407,-1,-1,-1,-1,-0.3027,-0.6201,-2.2954,-0.74150,-0.8608
157,train,728009,405000,2013-08-01,present,system engineer,Hyderabad,m,1989-05-17,77.00,...,-1,-1,-1,-1,-1,-0.0154,-2.1186,0.1637,1.66720,-1.6273
273,train,342928,325000,2014-12-01,present,system engineer,Hyderabad,m,1991-06-12,71.00,...,407,-1,-1,-1,-1,-0.4173,0.8518,0.9260,-0.05527,0.0284
282,train,807970,350000,2014-02-01,2015-04-01 00:00:00,system engineer,Hyderabad,m,1992-01-19,84.00,...,-1,-1,-1,446,-1,0.8463,0.8784,1.0859,-0.48790,0.6721
429,train,1087295,330000,2014-12-01,present,system engineer,Hyderabad,f,1992-09-30,76.40,...,376,-1,-1,-1,-1,0.7027,0.5454,-0.9122,-1.62890,-0.4776
950,train,320646,405000,2012-10-01,present,system engineer,Hyderabad,m,1990-07-05,93.00,...,-1,-1,-1,-1,-1,-0.5719,-0.3183,-0.9245,0.64983,-1.5513
1179,train,970373,325000,2014-12-01,present,system engineer,Hyderabad,m,1992-09-18,83.40,...,-1,-1,548,-1,-1,0.9900,-0.2871,0.4711,-1.88240,-0.6692
1207,train,600127,325000,2014-02-01,present,system engineer,Hyderabad,m,1991-07-27,90.00,...,-1,-1,516,-1,-1,0.1282,0.8784,-0.4511,0.27270,1.2470
1594,train,191027,350000,2011-06-01,2013-06-01 00:00:00,system engineer,Hyderabad,f,1986-10-23,81.60,...,-1,-1,-1,-1,-1,0.2009,-0.4353,-0.0537,-1.34780,0.5024
2595,train,344572,470000,2012-10-01,2015-05-01 00:00:00,system engineer,Hyderabad,m,1991-02-23,88.00,...,-1,-1,-1,-1,-1,-1.6538,0.3838,0.0552,1.23733,0.0284
2715,train,192591,500000,2011-12-01,2015-04-01 00:00:00,system engineer,Hyderabad,m,1990-03-26,83.00,...,-1,-1,-1,-1,-1,-0.2628,0.6568,0.8171,0.88480,-1.7093
3660,train,716336,400000,2014-02-01,2015-07-01 00:00:00,system engineer,Hyderabad,m,1991-04-18,81.50,...,-1,-1,-1,-1,-1,1.4208,0.3789,0.9322,1.41360,0.2889

# To retrive the IDs only of those who scored above 65% from Mechanical Engineering

In [6]:
df.loc[(df.Specialization=='mechanical engineering')&(df.collegeGPA>65),['ID']]

           ID
45    1230582
63     636871
123    312164
140    633445
191    531765
...       ...
3849  1002611
3909   628271
3916   530146
3951   885459
3980   197796

[151 rows x 1 columns]

# To retrive data of Software Engineer who are paid more than 3L

In [7]:
df.loc[(df.Designation=='software engineer')& (df.Salary>300000)]

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
19,train,466888,325000,2014-09-01,present,software engineer,Pune,f,1990-11-30,79.00,...,-1,-1,-1,-1,-1,0.8192,0.2668,-0.2714,-0.40780,-0.1295
20,train,140069,320000,2010-11-01,2012-09-01 00:00:00,software engineer,Bangalore,f,1988-07-25,91.20,...,-1,-1,-1,-1,-1,-0.1082,0.9688,0.5269,-0.29020,0.3444
31,train,1094324,340000,2014-08-01,2015-04-01 00:00:00,software engineer,Bangalore,m,1992-10-23,77.20,...,407,-1,-1,-1,-1,-0.0154,1.2114,1.0859,-1.50210,0.2889
48,train,338428,390000,2013-09-01,present,software engineer,Bangalore,m,1991-02-28,86.60,...,346,-1,-1,-1,-1,-2.5039,0.0328,0.3817,0.26793,0.5024
52,train,794209,400000,2015-04-01,present,software engineer,Navi Mumbai,m,1992-03-09,85.20,...,-1,-1,-1,-1,-1,1.1336,0.3789,1.0859,0.65300,0.2889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3970,train,1092890,310000,2014-04-01,present,software engineer,Navi Mumbai,m,1992-06-20,82.80,...,-1,-1,-1,-1,-1,-0.3027,-0.1206,0.3174,-0.36120,-0.2859
3977,train,217036,415000,2011-09-01,present,software engineer,Mumbai,m,1990-02-27,62.00,...,-1,-1,-1,-1,-1,-1.9629,-0.2793,-0.3440,0.53230,-0.1295
3978,train,1274658,320000,2013-08-01,2014-01-01 00:00:00,software engineer,Hyderabad,f,1991-04-24,89.70,...,-1,-1,-1,-1,-1,0.2718,1.2114,0.4711,-0.10760,0.8637
3979,train,212055,550000,2013-07-01,2014-04-01 00:00:00,software engineer,Bangalore,m,1989-07-22,69.16,...,-1,-1,-1,-1,-1,-0.5719,0.5008,-0.4891,0.41480,-1.2354
3984,train,305041,480000,2011-12-01,present,software engineer,Gurgaon,f,1990-01-18,89.80,...,-1,-1,-1,-1,-1,-0.2628,0.1888,0.3817,-0.29020,1.6082